# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ngo8OhqwcHJ4Ia2sciqmdnCQ8wzX_coD
"""

!pip install yfinance pandas matplotlib
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

!ls /content/*.csv

tickers = {
    "AAPL": "1y",
    "MSFT": "2y",
    "AMZN": "3y",
    "TSLA": "4y",
    "NVDA": "5y"
}

data = {}

for t, period in tickers.items():
    df = yf.download(t, period=period)
    df = df.dropna()

    data[t] = df

    df.to_csv(f"{t}.csv")

import datetime

def completeness(df):
    return 1 - df.isnull().sum().sum() / df.size


def latency(df):
    latest = df.index.max().date()
    today = datetime.date.today()
    return (today - latest).days


def accuracy(df):
    return ((df["Close"] <= df["High"]) & (df["Close"] >= df["Low"])).mean()


def consistency(df):
    return ((df["Open"] > 0) & (df["Close"] > 0) & (df["High"] >= df["Low"])).mean()


def compute_kpis(df):
    return {
        "Completeness": completeness(df),
        "Latency": latency(df),
        "Accuracy": accuracy(df),
        "Consistency": consistency(df)
    }

import pandas as pd

results = []

for t in data:
    kpis = compute_kpis(data[t])
    kpis["Ticker"] = t
    results.append(kpis)

kpi_df = pd.DataFrame(results)
kpi_df

for t, df in data.items():
    plt.figure(figsize=(10,4))
    plt.plot(df.index, df["Close"])
    plt.title(t + " Closing Price")
    plt.show()